jobPortalApp/urls.py
from unicodedata import name
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/', views.home, name="home"),
    path('home-redirect/', views.homeRedirect, name="homeRedirect"),
    path('', views.redirectLogin, name="redirectLogin"),
    path('creatt/', views.index),
    path('home/apply-job', views.applyJob, name="applyJob"),
    path('job-search/', views.jobSearch, name="jobSearch"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('login-process/', views.loginProcess, name="loginProcess"),
    path('logout/', views.logout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('profile/seeker-edit-profile', views.seekerEdit, name="seekerEdit"),
    path('profile/seeker-delete-account',
         views.seekerDeleteAccount, name="seekerDeleteAccount"),
    path('profile/seeker-change-profile',
         views.seekerChangeProfle, name="seekerChangeProfle"),
    path('profile/seeker-change-password',
         views.seekerChangePassword, name="seekerChangePassword"),
    path('seeker-resume/', views.seekerView, name="seekerView"),
    path('profile/seeker-edit-process',
         views.seekerEditProcess, name="seekerEditProcess"),
    path('profile/provider-change-profile',
         views.providerChangeProfle, name="providerChangeProfle"),
    path('profile/provider-delete-account',
         views.providerDeleteAccount, name="providerDeleteAccount"),
    path('profile/provider-change-password',
         views.providerChangePassword, name="providerChangePassword"),
    path('profile/provider-edit-profile',
         views.providerEdit, name="providerEdit"),
    path('profile/provider-edit-process',
         views.providerEditProcess, name="providerEditProcess"),
    path('profile/provider-add-job', views.providerAddJob, name="providerAddJob"),
    path('profile/provider-add-job-process',
         views.providerAddJobProcess, name="providerAddJobProcess"),
    path('profile/view-post/', views.providerViewPost, name="providerViewPost"),
    path('profile/view-applicant', views.providerViewApplicant,
         name="providerViewApplicant"),
    path('profile/view-applicant-resume', views.providerViewApplicantResume,
         name="providerViewApplicantResume"),
    path('home/view-post/', views.indexViewPost, name="indexViewPost"),
    path('profile/provider-edit-job',
         views.providerEditJob, name="providerEditJob"),
    path('profile/provider-deactivate-job',
         views.providerDeactivateJob, name="providerDeactivateJob"),
    path('profile/provider-activate-job',
         views.providerActivateJob, name="providerActivateJob"),
    path('profile/provider-edit-job-process',
         views.providerEditJobProcess, name="providerEditJobProcess"),
    path('manage_user/', views.manage_user, name="manage_user"),
    path('admin-login/', views.admin_login, name="admin_login"),
    path('admin-logout/', views.admin_logout, name="admin_logout"),
    path('admin-login-process/', views.admin_login_process, name="admin_login_process"),
    path('manage_user/activate_user',views.admin_activate_user, name="admin_activate_user"),
    path('manage_user/deactivate_user',views.admin_deactivate_user, name="admin_deactivate_user"),
    path('admin-edit-user/', views.admin_edit_user, name="admin-edit-user"),
    path('admin-edit-user-process/', views.admin_edit_user_process,name="admin-edit-user-process"),
    path('company/', views.company, name="company"),
    path('admin-edit-company/', views.admin_edit_company,name="admin-edit-company"),
    path('admin-edit-company-process/', views.admin_edit_company_process,name="admin-edit-company-process"),
    path('company/activate_company', views.admin_activate_company,name="admin_deactivate_company"),
    path('company/deactivate_company', views.admin_deactivate_company,name="admin_activate_company"),
    path('jobs/', views.jobs, name="jobs"),
    path('admin-edit-job/', views.admin_edit_job,name="admin-edit-job"),
    path('admin-edit-job-process/', views.admin_edit_job_process,name="admin-edit-job-process"),
    path('jobs/activate_job', views.admin_activate_jobs,name="admin_activate_jobs"),
    path('jobs/deactivate_job', views.admin_deactivate_jobs,name="admin_deactivate_jobs"),
    path('activity_logs/', views.activity_logs, name="activity_logs"),
    path('users-report/', views.users_report, name="users_report"),
    path('activity-report/', views.activity_report, name="activity_report"),
    path('job-report/', views.job_report, name="job_report"),
    path('company-report/', views.company_report, name="company_report"),
]

webProject/urls.py
from django.contrib import admin
from django.urls import path, include
from jobPortalApp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobPortalApp.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobPortalApp/models.py
from django.db import models
from django.conf import settings
from django.core.validators import FileExtensionValidator
# Create your models here.

# maverick


class SEEKER(models.Model):
    user_id = models.IntegerField(null=True)
    username = models.TextField(null=True)
    fullname = models.CharField(max_length=255, null=True)
    experience = models.TextField(null=True)
    about = models.TextField(null=True)
    status = models.TextField(null=True)

    def __str__(self):
        return self.username

# maverick


class COMPANY(models.Model):
    user_id = models.IntegerField(null=True)
    username = models.TextField(null=True)
    name = models.CharField(max_length=255, null=True)
    description = models.TextField(null=True)
    city = models.CharField(max_length=255, null=True)
    country = models.CharField(max_length=255, null=True)
    status = models.TextField(null=True)

    def __str__(self):
        return self.username


class SKILL(models.Model):
    skillname = models.TextField(unique=True)

    def __str__(self):
        return self.skillname


class SEEKERSKILL(models.Model):
    skill_id = models.IntegerField()
    user_id = models.IntegerField()


class JOBSKILL(models.Model):
    skill_id = models.IntegerField()
    job_id = models.IntegerField()


class RESUME(models.Model):
    user_id = models.IntegerField(null=True)
    resume = models.FileField(upload_to=settings.MEDIA_ROOT, null=True,validators=[FileExtensionValidator(allowed_extensions=['pdf'])])


class JOB(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    salary = models.IntegerField()
    type = models.CharField(max_length=255)
    company_id = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    status = models.TextField(null=True)

    def __str__(self):
        return self.name


class APPLICATION(models.Model):
    user_id = models.IntegerField(null=True)
    job_id = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)


class PROFILE(models.Model):
    user_id = models.IntegerField(null=True)
    profile = models.FileField(upload_to=settings.MEDIA_ROOT, null=True)

class ACTIVITY(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    user_id = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

jobPortalApp/views.py
from fileinput import filename
import imp
from pydoc import describe
import re
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.models import User
from .models import *
from .forms import *
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.core.mail import send_mail
from django.http import FileResponse
import io
# from reportlab.pdfgen import canvas
# from reportlab.lib.units import inch
# from reportlab.lib.pagesizes import letter
# from .models import Event, Venue
# from .forms import VenueForm, EventForm

# Create your views here.
def index(request):
    return render(request, "jobPortalApp/index.html")


def redirectLogin(request):
    return redirect('login')

def homeRedirect(request):
    if 'job-search' in request.session:
        del request.session['job-search']
    if 'job-type' in request.session:
        del request.session['job-type']
    if 'job-country' in request.session:
        del request.session['job-country']
    if 'job-city' in request.session:
        del request.session['job-city']
    request.session.modified = True
    return redirect('home')

def home(request):
    # return HttpResponse('Home Page')
    if 'user_id' not in request.session:
        return redirect('login')
    else:
        job_title = request.session['job_type']
        user_id = request.session['user_id']
        profile = PROFILE.objects.filter(user_id=user_id)
        user_name = ""
        if job_title == "Job Seeker":
            seeker_name = SEEKER.objects.get(user_id=user_id)
            user_name = seeker_name.fullname
        elif job_title == "Job Provider":
            provider_name = COMPANY.objects.get(user_id=user_id)
            user_name = provider_name.name
        job_search = ""
        job_type = False
        job_country = False
        job_city = False
        default_all_jobs = JOB.objects.filter(status='Activated')
        default_all_jobs_skills = {}
        default_all_jobs_apllication = {}
        for default_all_job in default_all_jobs:
            job_skillnames_per_jobs = []
            job_skills_per_jobs = JOBSKILL.objects.filter(
                job_id=default_all_job.id)
            application_per_jobs = APPLICATION.objects.filter(
                job_id=default_all_job.id).count()
            default_all_jobs_apllication[default_all_job.id] = str(application_per_jobs)
            for job_skills_per_job in job_skills_per_jobs:
                skills = SKILL.objects.get(id=job_skills_per_job.skill_id)
                job_skillnames_per_jobs.append(skills.skillname)
            default_all_jobs_skills[default_all_job.id] = job_skillnames_per_jobs
        if 'job-search' and 'job-type' and 'job-country' and 'job-city' in request.session:
            job_search = request.session['job-search']
            job_type = request.session['job-type']
            job_country = request.session['job-country']
            job_city = request.session['job-city']
            if job_country == "":
                job_country = False
            if job_type == "":
                job_type = False
            if job_city == "":
                job_city = False
        is_non_empty = bool(job_search)
        jobs = []
        company_jobs_ids = []
        skillnames_per_jobs = {}
        applications_per_jobs = {}
        applications_per_jobs = {}
        searcher = ""
        # search city country type
        if is_non_empty != False and job_city != False and job_country != False and job_type != False:
            company_ids = ""
            if COMPANY.objects.filter(city=job_city, country=job_country).exists():
                company_ids = COMPANY.objects.filter(
                    city=job_city, country=job_country)
            if JOB.objects.filter(name__contains=job_search,status="Activated").exists():
                for company_id in company_ids:
                    filtered_jobs = JOB.objects.filter(
                        name__contains=job_search, company_id=company_id.user_id, type=job_type)
                    jobs.append(JOB.objects.filter(
                        name__contains=job_search, company_id=company_id.user_id, type=job_type))
                    for filtered_job in filtered_jobs:
                        company_jobs_ids.append(filtered_job.id)
            else:
                if SKILL.objects.filter(skillname=job_search).exists():
                    skillname = SKILL.objects.get(skillname=job_search)
                    job_ids = JOBSKILL.objects.filter(skill_id=skillname.id)
                    for job_id in job_ids:
                        for company_id in company_ids:
                            jobs.append(JOB.objects.filter(
                                id=job_id.job_id, company_id=company_id.user_id, type=job_type,status="Activated"))
                            filtered_jobs = JOB.objects.filter(
                                id=job_id.job_id, company_id=company_id.user_id, type=job_type,status="Activated")
                            for filtered_job in filtered_jobs:
                                company_jobs_ids.append(filtered_job.id)
            searcher = job_search + " " + job_type + " in " + job_country + " - " + job_city
        # search city type
        elif is_non_empty != False and job_type != False and job_city != False:
            company_ids = ""
            if COMPANY.objects.filter(city=job_city).exists():
                company_ids = COMPANY.objects.filter(city=job_city)
            if JOB.objects.filter(name__contains=job_search, type=job_type).exists():
                for company_id in company_ids:
                    filtered_jobs = JOB.objects.filter(
                        name__contains=job_search, type=job_type, company_id=company_id.user_id,status="Activated")
                    jobs.append(JOB.objects.filter(
                        name__contains=job_search, type=job_type, company_id=company_id.user_id,status="Activated"))
                    for filtered_job in filtered_jobs:
                        company_jobs_ids.append(filtered_job.id)
            else:
                if SKILL.objects.filter(skillname=job_search).exists():
                    skillname = SKILL.objects.get(skillname=job_search)
                    job_ids = JOBSKILL.objects.filter(skill_id=skillname.id)
                    for job_id in job_ids:
                        for company_id in company_ids:
                            jobs.append(JOB.objects.filter(
                                id=job_id.job_id, type=job_type, company_id=company_id.user_id,status="Activated"))
                            filtered_jobs = JOB.objects.filter(
                                id=job_id.job_id, type=job_type, company_id=company_id.user_id,status="Activated")
                            for filtered_job in filtered_jobs:
                                company_jobs_ids.append(filtered_job.id)
            searcher = job_search + " " + job_type + " in " + job_city
        # search city country
        elif is_non_empty != False and job_country != False and job_city != False:
            company_ids = ""
            if COMPANY.objects.filter(country=job_country, city=job_city).exists():
                company_ids = COMPANY.objects.filter(
                    country=job_country, city=job_city)
            if JOB.objects.filter(name__contains=job_search).exists():
                for company_id in company_ids:
                    filtered_jobs = JOB.objects.filter(
                        name__contains=job_search, company_id=company_id.user_id,status="Activated")
                    jobs.append(JOB.objects.filter(
                        name__contains=job_search, company_id=company_id.user_id,status="Activated"))
                    for filtered_job in filtered_jobs:
                        company_jobs_ids.append(filtered_job.id)
            else:
                if SKILL.objects.filter(skillname=job_search).exists():
                    skillname = SKILL.objects.get(skillname=job_search)
                    job_ids = JOBSKILL.objects.filter(skill_id=skillname.id)
                    for job_id in job_ids:
                        for company_id in company_ids:
                            jobs.append(JOB.objects.filter(
                                id=job_id.job_id, company_id=company_id.user_id,status="Activated"))
                            filtered_jobs = JOB.objects.filter(
                                id=job_id.job_id, company_id=company_id.user_id,status="Activated")
                            for filtered_job in filtered_jobs:
                                company_jobs_ids.append(filtered_job.id)
            searcher = job_search + " in " + job_country + " - " + job_city
        # search country type
        elif is_non_empty != False and job_type != False and job_country != False:
            company_ids = ""
            if COMPANY.objects.filter(country=job_country).exists():
                company_ids = COMPANY.objects.filter(country=job_country)
            if JOB.objects.filter(name__contains=job_search, type=job_type).exists():
                for company_id in company_ids:
                    filtered_jobs = JOB.objects.filter(
                        name__contains=job_search, type=job_type, company_id=company_id.user_id,status="Activated")
                    jobs.append(JOB.objects.filter(
                        name__contains=job_search, type=job_type, company_id=company_id.user_id,status="Activated"))
                    for filtered_job in filtered_jobs:
                        company_jobs_ids.append(filtered_job.id)
            else:
                if SKILL.objects.filter(skillname=job_search).exists():
                    skillname = SKILL.objects.get(skillname=job_search)
                    job_ids = JOBSKILL.objects.filter(skill_id=skillname.id)

jobPortalApp/templates/jobPortalApp/pages/profile/provider/add-edit-info.html
{#for job provider/company edit info#}
{% extends "jobPortalApp/base.html" %}
{% load static %}
{% block title %}Edit Provider Info{% endblock title %}

{% block content %}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<nav class="flex-shrink-0 flex justify-between items-center bg-white py-[15px] pl-[150px] pr-[50px]">
    <a href="../../home-redirect/">
        <img src="{% static 'images/logo-blue.png' %}" alt="" class="w-[120px] h-[25px]">
    </a>
    <div x-data="{ show: false }" class="relative">
        <div class="inline-flex items-center gap-x-2">
            <div class="flex flex-col items-end">
                {% if not provider.name%}
                <span>Not Set</span>
                {% else %}
                <span>{{provider.name}}</span>
                {% endif%}
                <span class="text-xs font-light">{{user_type}}</span>
            </div>
            
            {% if profile %}
            {% for prof in profile%}
            <img src="{{prof.profile.url}}" alt="" class="w-[36px] h-[36px]" @click="show = ! show">
            {% endfor %}
            {% else %}
            <img src="{% static 'images/profile.svg' %}" alt="" class="w-[36px] h-[36px]" @click="show = ! show">
            {% endif %}
        </div>
        <div x-show="show"
            class="absolute bg-white p-[12px] right-0 w-[120px] rounded-[4px] shadow-[0_0_40px_0_rgba(0,0,0,0.1)]">
            <a href="../profile"
                class="block w-full font-light p-2 text-center hover:bg-light-grayish-blue rounded-[4px]">
                Profile
            </a>
            <a id="logout-btn" class="block w-full font-light p-2 text-center hover:bg-light-grayish-blue rounded-[4px]">
                Logout
            </a>
        </div>
    </div>
</nav>
        <main class="flex flex-col gap-y-[44px] flex-grow px-[200px] py-[60px]">
            
        <section class="flex-grow flex flex-col gap-y-[55px] bg-white min-h-[400px] p-[36px]">
            <div class="flex-shrink-0 flex flex-col gap-y-[36px]">
                <div class="flex justify-between items-start">
                    <a href="../profile" class="flex items-center gap-x-2">
                        <span><img src="{% static 'images/chevron-left.svg' %}" alt=""></span>
                        <span class="uppercase text-sm font-light">Go Back</span>
                    </a>
                </div>
                <div class="text-[28px] font-semibold italic ml-[42px]">Setting Up Information</div>
            </div>
            <div class="flex flex-col gap-y-[50px] px-[42px]">
                <div class="flex flex-col gap-y-[34px]">
                    <form id="provider-profile-form" action="../profile/provider-edit-process" method="POST">
                        {% csrf_token %}
                    <div class="text-[22px] font-semibold italic">Job Provider Information</div>
                    <div class="flex flex-col gap-y-[24px]">
                        <div class="flex flex-col gap-y-[5px]">
                            <span class="label">Name</span>
                            {% if not provider.name %}
                            <input type="text" name="name" id="name" placeholder="Enter job provider name"
                                class="input-1px w-[250px]">
                            {% else %}
                            <input type="text" name="name" id="name" value="{{provider.name}}"
                                class="input-1px w-[250px]">
                            {% endif %}
                        </div>
                        <div class="flex flex-col gap-y-[5px]">
                            <span class="label">Description</span>
                            
                            {% if not provider.description %}
                            <textarea name="description" id="description" rows="8" placeholder="Enter informations about the job provider"
                                class="input-1px"></textarea>
                            {% else %}
                            <textarea name="description" id="description" rows="8"
                                class="input-1px">{{provider.description}}</textarea>
                            {% endif %}
                        </div>
                        <div class="flex gap-x-[20px]">
                            <div class="flex flex-col gap-y-[5px]">
                                <span class="label">Country</span>
                                {% if not provider.country %}
                                <select name="country" id="id_country" required class="select-2 w-[250px]" onchange="countyChoice()">
                                    <option value="" selected hidden>Select Country</option>
                                    <option class="country" value="China">China</option>
                                    <option class="country" value="Russia">Russia</option>
                                    <option class="country" value="South Korea">South Korea</option>
                                    <option class="country" value="Japan">Japan</option>
                                </select>
                                {% else %}
                                <select name="country" id="id_country" required class="select-2 w-[250px]" onchange="countyChoice()">
                                    <option value="{{provider.country}}" selected hidden>{{provider.country}}</option>
                                    <option class="country" value="China">China</option>
                                    <option class="country" value="Russia">Russia</option>
                                    <option class="country" value="South Korea">South Korea</option>
                                    <option class="country" value="Japan">Japan</option>
                                </select>
                                {% endif %}
                            </div>
                            <div class="flex flex-col gap-y-[5px]">
                                <span class="label">City</span>
                                {% if not provider.city %}
                                <select name="city" id="id_city" required class="select-2 w-[250px]">
                                    <option  value="" selected hidden>Select City</option>
                                    <option class="China" value="Beijing" style="display: block;">Beijing</option>
                                    <option class="China" value="Macau" style="display: block;">Macau</option>
                                    <option class="Japan" value="Inuyama" style="display: block;">Inuyama</option>
                                    <option class="Japan" value="Toyota" style="display: block;">Toyota</option>
                                    <option class="Russia" value="Abakan" style="display: block;">Abakan</option>
                                    <option class="Russia" value="Beslan" style="display: block;">Beslan</option>
                                    <option class="South Korea" value="Seoul" style="display: block;">Seoul</option>
                                    <option class="South Korea" value="Busan" style="display: block;">Busan</option>
                                </select>
                                {% else %}
                                <select name="city" id="id_city" required class="select-2 w-[250px]">
                                    <option value="{{provider.city}}" selected hidden>{{provider.city}}</option>
                                    <option class="China" value="Beijing" style="display: block;">Beijing</option>
                                    <option class="China" value="Macau" style="display: block;">Macau</option>
                                    <option class="Japan" value="Inuyama" style="display: block;">Inuyama</option>
                                    <option class="Japan" value="Toyota" style="display: block;">Toyota</option>
                                    <option class="Russia" value="Abakan" style="display: block;">Abakan</option>
                                    <option class="Russia" value="Beslan" style="display: block;">Beslan</option>
                                    <option class="South Korea" value="Seoul" style="display: block;">Seoul</option>
                                    <option class="South Korea" value="Busan" style="display: block;">Busan</option>
                                </select>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
            <button class="btn self-end" id="info-save">Save</button>
        </section>
    </main>

    <script>
        
    logout_open = document.getElementById('logout-btn');
    logout_open.onclick = function() {
        swal({
            title: "Logout",
            text: "Are you sure you want to logout?",
            icon: "info",
                buttons: {
                yes: {
                    text: "Yes",
                    value: "yes"
                },
                no: {
                    text: "No",
                    value: "no",
                }
                }
        }).then((value) => {
                if (value === "yes") {
                // Add Your Custom Code for CRUD
                window.location.href="../../logout"
                }
        });
    };
        // window.onclick = function(){
        //     document.getElementById('logout-div').style.display = "None";
        // }

        btn_save = document.getElementById('info-save');

        btn_save.onclick = function () {
            document.getElementById('provider-profile-form').submit();
        };
        function countyChoice(){

            d = document.getElementById("id_country").value;
            var items2 = document.getElementsByClassName('country');
            for (var i=0; i < items2.length; i++) {
                if (items2[i].value != d){
                    var items3 = document.getElementsByClassName(items2[i].value);
                    for (var j=0; j < items3.length; j++) {
                        items3[j].style.display = "none";
                    }
                }
            }
            var items3 = document.getElementById('id_city');
            var items = document.getElementsByClassName(d);
            items3.selectedIndex = items[0].index
            for (var i=0; i < items.length; i++) {
                items[i].style.display = "block";
                
            }
            
        }

    </script>
{% endblock content %}


{# I comment up the nav part since it already exist in base.html #}
{#<body class="flex flex-col bg-very-pale-blue">#}
{#    <nav class="flex-shrink-0 flex justify-between items-center bg-white py-[15px] pl-[150px] pr-[50px]">#}
{#        <img src="assets/logo-blue.png" alt="" class="w-[120px] h-[25px]">#}
{#        <div x-data="{ show: false }" class="relative">#}
{#            <div class="inline-flex items-center gap-x-2">#}
{#                <div class="flex flex-col items-end">#}
{#                    <span>Sarah Morrison</span>#}
{#                    <span class="text-xs font-light">Job Title</span>#}
{#                </div>#}
{#                <img src="{% static 'images/profile.svg' %}" alt="" class="w-[36px] h-[36px]" @click="show = ! show">#}
{#            </div>#}
{#            <div x-show="show"#}
{#                class="absolute bg-white p-[12px] right-0 w-[120px] rounded-[4px] shadow-[0_0_40px_0_rgba(0,0,0,0.1)]">#}
{#                <a href="" class="block w-full font-light p-2 text-center hover:bg-light-grayish-blue rounded-[4px]">#}
{#                    Profile#}
{#                </a>#}
{#                <a href="" class="block w-full font-light p-2 text-center hover:bg-light-grayish-blue rounded-[4px]">#}
{#                    Logout#}
{#                </a>#}
{#            </div>#}
{#        </div>#}
{#    </nav>#}
{#</body>#}